backend:
  #name: github
  name: git-gateway
  #repo: vosaul/PARETO
  repo: HelloPareto/blog
  branch: main
publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

collections:

- label: Content
  name: content
  editor:
    preview: true
  folder: /content/blog/
  fields:
  - name: layout
    hidden: string
    default: post
  - name: title
    widget: string
  - name: seoTitleTag
    widget: string
  - name: date
    widget: datetime
  - name: slug
    widget: string
  - name: description
    widget: text
  - name: seoMetaDescription
    widget: text
  - name: category
    widget: string
  - name: image
    widget: image
  - name: mainImage
    widget: image
  - name: author
    widget: string
  - name: relatedArticles
    widget: list
    fields:
    - {name: title, widget: string}
    - {name: slug, widget: string}
    - {name: categoryName, widget: string}
  - name: publishedOn
    widget: datetime     
  - name: updatedAt
    widget: datetime     
  - name: createdAt
    widget: datetime     
  - name: body
    widget: markdown